name: builder
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/*'
      - 'studio/*'
      - 'public/*'
      - 'README.md'
      - '.*'
      - '!.github'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
        env:
          NEXT_PUBLIC_SANITY_DATASET: production
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
